### ISSUE TITLE
Avoid to configure username and password for UI auth in the values file

### ISSUE THREAD

**Issue by caiofralmeida** [eshepelyuk/cmak-operator#40]
Hi guys!

We would like to configure basic authentication without expose the user and password in the values. We have a integration with Vault secrets management that [injects secret automatically](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/) when the pods are starting.

I have been thinking in two ways to avoid expose user and password in values.

1. Give a new configuration on values to inform the extra Envs.

```yaml
ui:
  extraEnvs:
    KAFKA_MANAGER_USERNAME: vault:/secrets/data/cmak#username
    KAFKA_MANAGER_PASSWORD: vault:/secrets/data/cmak#password
```

2. Give a new configuration on values to generate a new k8s secret and bind it with deployment.

```yaml
ui:
  secretName: cmak-secret
```
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: cmak-secret
  labels:
type: Opaque
data:
  username: vault:/secrets/data/cmak#username
  password: vault:/secrets/data/cmak#password
```

What do you think?

Thanks in advanced.
